---
- name: Copy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Ensure Prometheus service is running
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes
